name: JSON Schema Generation and Validation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: JSON Schema Generator
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v2

      # 2. Install dependencies using Yarn
      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      # 3. Run tests
      - uses: borales/actions-yarn@v4
        with:
          cmd: test

      # 4. Run the 'yarn generate' command to generate files
      - uses: borales/actions-yarn@v4
        with:
          cmd: generate

      # 5. Check for changes, commit, and push
      - name: Commit and Push changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .

          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Generated files via GitHub Actions"

            # Pull the latest changes from the remote before pushing
            git pull --rebase origin main

            # Push the changes to the main branch
            git push origin HEAD:main
          fi
